services:
  blast-geth:
    build:
      context: .
      dockerfile: geth/Dockerfile
    volumes:
      - /var/lib/blast:/blast
      - ${PWD}/geth-logs:/geth-logs
    ports:
      - 127.0.0.1:9545:8545 # http rpc
      - 127.0.0.1:9546:8546 # ws rpc
      - 127.0.0.1:9551:8551 # engine auth
      - 31303:30303 # p2p
      - 31303:30303/udp # p2p
      - 127.0.0.1:6060:6060 # metrics
    networks:
      - blast-network
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped
    stop_grace_period: 5m

  op-node:
    build:
      context: .
      dockerfile: op-node/Dockerfile
    volumes:
      - /var/lib/blast:/blast
    ports:
      - '9222:9222' # p2p
      - '9222:9222/udp' # p2p
      - 127.0.0.1:7300:7300 # metrics
    depends_on:
      - blast-geth
    networks:
      - blast-network
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped
    stop_grace_period: 5m

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '127.0.0.1:9091:9090' # metrics
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheusdata
    volumes:
      - ${PWD}/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheusdata
    restart: unless-stopped
    depends_on:
      - blast-geth
      - op-node
    networks:
      - blast-network

networks:
  blast-network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

volumes:
  prometheus_data:
