apiVersion: 1

deleteDatasources:
- name: 'Prometheus'
- name: 'Prometheus-docker'

# Configured to add to existing Grafana server running on host machine.
datasources:
- name: Prometheus-docker
  type: prometheus
  access: proxy
  url: http://localhost:9091
  editable: true

- name: Prometheus
  type: prometheus
  access: proxy
  url: http://localhost:9090
  editable: true